// Code generated by bin/img2cpp and bin/gltf2cpp: the headers under test/data
// are checked in; regenerate them with the scripts in test/tools.

#include <cstdint>
#include <cstdlib>
#include <cstring>

#include "check.hpp"
#include "data/test_image_argb4444.hpp"
#include "data/test_image_gray1.hpp"
#include "data/test_image_rgb444.hpp"
#include "data/test_image_rgb565be.hpp"
#include "data/test_model.hpp"
#include "shapoco/gfx2d/surface_alloc.hpp"
#include "shapoco/gfx3d/gfx3d.hpp"

namespace g2 = shapoco::gfx2d;
namespace g3 = shapoco::gfx3d;

// Same formula as test/tools/make_test_image.py
static g2::Color testImagePixel(int x, int y) {
  return g2::makeColor((x * 19) % 256, (y * 36) % 256, (x * y * 7) % 256,
                       (x + y) % 5 == 0 ? 0 : 255);
}

static int absDiff(int a, int b) { return a > b ? a - b : b - a; }

// The generated texture must hold the source pixels within the quantization
// step of its format (the tool rounds, the library truncates: allow 1 step).
static void checkTexture(const g2::Texture &t, int stepR, int stepG, int stepB,
                         bool alpha, bool gray) {
  CHECK_EQ(t.width, 13);
  CHECK_EQ(t.height, 7);
  CHECK_EQ(t.stride, g2::minStride(t.format, 13));
  g2::Graphics2D g;  // only used for pixel reading via a temporary Surface
  g2::Surface s = {t.format, t.width, t.height, t.stride,
                   const_cast<void *>(t.pixels)};
  g.setTarget(s);
  for (int y = 0; y < 7; y++) {
    for (int x = 0; x < 13; x++) {
      g2::Color want = testImagePixel(x, y);
      g2::Color got = g.getPixel(x, y);
      if (gray) {
        CHECK_EQ(got, g2::gray1ToColor(g2::colorToGray1(want)));
        continue;
      }
      CHECK(absDiff(g2::colorR(got), g2::colorR(want)) <= stepR);
      CHECK(absDiff(g2::colorG(got), g2::colorG(want)) <= stepG);
      CHECK(absDiff(g2::colorB(got), g2::colorB(want)) <= stepB);
      if (alpha) CHECK(absDiff(g2::colorA(got), g2::colorA(want)) <= 17);
    }
  }
}

static void testImg2cpp() {
  CHECK_EQ((int)test_image_rgb565be::texture.format,
           (int)g2::PixelFormat::RGB565BE);
  CHECK_EQ((int)test_image_argb4444::texture.format,
           (int)g2::PixelFormat::ARGB4444);
  CHECK_EQ((int)test_image_rgb444::texture.format,
           (int)g2::PixelFormat::RGB444);
  CHECK_EQ((int)test_image_gray1::texture.format, (int)g2::PixelFormat::GRAY1);
  checkTexture(test_image_rgb565be::texture, 9, 5, 9, false, false);
  checkTexture(test_image_argb4444::texture, 17, 17, 17, true, false);
  checkTexture(test_image_rgb444::texture, 17, 17, 17, false, false);
  checkTexture(test_image_gray1::texture, 0, 0, 0, false, true);
}

static uint8_t arena[128 * 1024];

// Skips the node called `skip` and spins the node called `spin`
class TestVisitor : public g3::NodeVisitor {
 public:
  const char *skip = nullptr;
  const char *spin = nullptr;
  int visited = 0;
  bool onNode(const g3::Node &node, g3::mat4f &local) override {
    visited++;
    if (skip && node.name && std::strcmp(node.name, skip) == 0) return false;
    if (spin && node.name && std::strcmp(node.name, spin) == 0) {
      local = local * g3::mat4f::rotation(1.0f, {0, 1, 0});
    }
    return true;
  }
};

static int renderScene(g3::Graphics3D &r, const g2::Surface &s,
                       g3::NodeVisitor *v) {
  r.setPerspectiveProjection(1.0f, (float)s.width / s.height, 0.3f, 50.0f);
  r.beginScene();
  r.lookAt({2.5f, 2.0f, 3.0f}, {0, 0.3f, 0});
  r.enableParallelLight({-0.5f, -1, -0.4f}, {1, 1, 1, 1});
  r.enableEnvironmentLight({0.3f, 0.3f, 0.3f, 1});
  r.putScene(test_model::scene, v);
  r.endScene();
  r.beginRender();
  r.render(0, 0, s.width, s.height, s);
  r.endRender();
  return r.getStats().triCount;
}

static void testGltf2cpp() {
  // Structure produced from test/data/test_model.glb
  CHECK_EQ(test_model::scene.rootCount, 1);
  CHECK(test_model::scene.roots[0] == &test_model::node_Root);
  CHECK_EQ(test_model::node_Root.childCount, 3);
  CHECK(test_model::node_Root.children[0] == &test_model::node_Cube);
  CHECK(test_model::node_Root.children[1] == &test_model::node_Pyramid);
  CHECK(test_model::node_Root.children[2] == &test_model::node_Axes);
  // LINES primitive: unlit vertex colors, no material in the glTF -> default
  // material
  const g3::Primitive &axes = test_model::node_Axes.mesh->primitives[0];
  CHECK_EQ((int)axes.type, (int)g3::PrimitiveType::LINES);
  CHECK_EQ(axes.indexCount, 6);
  CHECK((axes.material->flags & g3::MaterialFlags::VERTEX_COLOR) != 0);
  CHECK_EQ(axes.vertexBuffer->vertices[1].color, 0xFFFF0000u);
  CHECK_EQ(test_model::node_Pyramid.childCount, 1);
  CHECK(std::strcmp(test_model::node_Tip_Pyramid.name, "Tip Pyramid") == 0);
  CHECK(test_model::node_Cube.mesh != nullptr);
  CHECK_EQ(test_model::node_Cube.mesh->primitiveCount, 1);
  const g3::Primitive &cube = test_model::node_Cube.mesh->primitives[0];
  CHECK_EQ(cube.vertexBuffer->vertexCount, 24);
  CHECK_EQ(cube.indexCount, 36);
  CHECK(cube.material->texture != nullptr);
  CHECK((cube.material->flags & g3::MaterialFlags::TEXTURE) != 0);
  CHECK((cube.material->flags & g3::MaterialFlags::VERTEX_COLOR) != 0);
  CHECK_EQ(cube.material->texture->width, 16);
  // Pyramid: normals were generated, material is double-sided and red
  const g3::Primitive &pyr = test_model::node_Pyramid.mesh->primitives[0];
  CHECK((pyr.material->flags & g3::MaterialFlags::DOUBLE_SIDED) != 0);
  CHECK(pyr.material->diffuse.r > 0.8f && pyr.material->diffuse.g < 0.3f);
  float len = g3::length(pyr.vertexBuffer->vertices[4].normal);
  CHECK(len > 0.99f && len < 1.01f);
  CHECK(pyr.vertexBuffer->vertices[4].normal.y >
        0.9f);  // apex normal points up
  // Node transform: rotation of 45 degrees around Y and translation
  const g3::mat4f &m = test_model::node_Cube.transform;
  CHECK(std::abs(m.m[0] - 0.7071f) < 0.001f &&
        std::abs(m.m[12] + 0.8f) < 0.001f);

  // Traversal: everything draws, indices are valid, nothing is dropped
  g3::Graphics3D r;
  r.init(96, 64, arena, sizeof(arena));
  r.setClearColor({0, 0, 0, 1});
  g2::OwnedSurface a = g2::createSurface(g2::PixelFormat::RGB565BE, 96, 64);
  g2::OwnedSurface b = g2::createSurface(g2::PixelFormat::RGB565BE, 96, 64);
  int all = renderScene(r, a, nullptr);
  CHECK(all > 0);
  CHECK_EQ(r.getStats().badIndices, 0);
  CHECK_EQ(r.getStats().nodesDropped, 0);
  // Visitor: skipping the pyramid subtree removes its triangles and its child's
  TestVisitor v;
  v.skip = "Pyramid";
  int noPyramid = renderScene(r, b, &v);
  CHECK(noPyramid < all);
  CHECK_EQ(v.visited,
           4);  // Root, Cube, Pyramid, Axes (Pyramid's child not visited)
  // Visitor: modifying a transform changes the image but not the triangle count
  TestVisitor spin;
  spin.spin = "Cube";
  int spun = renderScene(r, b, &spin);
  CHECK(spun > 0);
  CHECK(std::memcmp(a.pixels(), b.pixels(), a.bytes()) != 0);
}

// A chain deeper than the state stack is cut off and counted, without crashing
static void testDeepTree() {
  static g3::Node chain[24];
  static const g3::Node *childPtr[24];
  for (int i = 0; i < 24; i++) {
    childPtr[i] = (i + 1 < 24) ? &chain[i + 1] : nullptr;
    chain[i] = {nullptr, g3::mat4f::translation(0.1f, 0, 0),
                test_model::node_Cube.mesh,
                (i + 1 < 24) ? &childPtr[i] : nullptr,
                (uint16_t)((i + 1 < 24) ? 1 : 0)};
  }
  g3::Graphics3D r;
  r.init(32, 32, arena, sizeof(arena));
  g2::OwnedSurface s = g2::createSurface(g2::PixelFormat::RGB565BE, 32, 32);
  r.setOrthographicProjection(-4, 4, -4, 4, 0.1f, 10);
  r.beginScene();
  r.translate(0, 0, -5);
  r.putNode(chain[0]);
  r.endScene();
  r.beginRender();
  r.render(0, 0, 32, 32, s);
  r.endRender();
  g3::Stats st = r.getStats();
  CHECK(st.nodesDropped > 0);
  CHECK(st.triCount > 0);
  CHECK_EQ(st.badIndices, 0);
}

void testTools() {
  testImg2cpp();
  testGltf2cpp();
  testDeepTree();
}
