#ifndef TEST_IMAGE_GRAY1_TEST_IMAGE_GRAY1_HPP
#define TEST_IMAGE_GRAY1_TEST_IMAGE_GRAY1_HPP

// Generated by img2cpp from test_image.png
// 13x7, gray1, dither=none, 14 bytes

#include "shapoco/gfx2d/surface.hpp"

namespace test_image_gray1 {

alignas(4) static const uint8_t textureData[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0xF8, 0x07, 0xF8, 0x1F, 0xF8, 0x7F, 0xF8,
};

static const shapoco::gfx2d::Texture texture = {
  shapoco::gfx2d::PixelFormat::GRAY1, 13, 7, 2, textureData,
};

}  // namespace test_image_gray1

#endif
