#ifndef TEST_MODEL_PACKED_TEST_MODEL_PACKED_HPP
#define TEST_MODEL_PACKED_TEST_MODEL_PACKED_HPP

// Generated by gltf2cpp from test_model.glb
// Draw with Graphics3D::putScene(scene) or putNode(node_...).

#include "shapoco/gfx3d/gfx3d.hpp"

namespace test_model_packed {

namespace g2 = shapoco::gfx2d;
namespace g3 = shapoco::gfx3d;

static_assert(g3::MODEL_FORMAT_VERSION >= 1,
              "this header needs a newer ShapoGFX (gfx3d.hpp MODEL_FORMAT_VERSION)");

// mesh 0 primitive 0: 24 vertices, 36 indices
static const g3::PackedVertex mesh0Prim0Vertices[] = {
  {{32767, -32767, 32767}, {0, 1024}, {127, 0, 0}, {255, 128, 128}},
  {{32767, -32767, -32767}, {1024, 1024}, {127, 0, 0}, {255, 128, 128}},
  {{32767, 32767, -32767}, {1024, 0}, {127, 0, 0}, {255, 128, 128}},
  {{32767, 32767, 32767}, {0, 0}, {127, 0, 0}, {255, 128, 128}},
  {{-32767, -32767, -32767}, {0, 1024}, {-127, 0, 0}, {128, 255, 128}},
  {{-32767, -32767, 32767}, {1024, 1024}, {-127, 0, 0}, {128, 255, 128}},
  {{-32767, 32767, 32767}, {1024, 0}, {-127, 0, 0}, {128, 255, 128}},
  {{-32767, 32767, -32767}, {0, 0}, {-127, 0, 0}, {128, 255, 128}},
  {{-32767, 32767, 32767}, {0, 1024}, {0, 127, 0}, {128, 128, 255}},
  {{32767, 32767, 32767}, {1024, 1024}, {0, 127, 0}, {128, 128, 255}},
  {{32767, 32767, -32767}, {1024, 0}, {0, 127, 0}, {128, 128, 255}},
  {{-32767, 32767, -32767}, {0, 0}, {0, 127, 0}, {128, 128, 255}},
  {{-32767, -32767, -32767}, {0, 1024}, {0, -127, 0}, {255, 128, 128}},
  {{32767, -32767, -32767}, {1024, 1024}, {0, -127, 0}, {255, 128, 128}},
  {{32767, -32767, 32767}, {1024, 0}, {0, -127, 0}, {255, 128, 128}},
  {{-32767, -32767, 32767}, {0, 0}, {0, -127, 0}, {255, 128, 128}},
  {{-32767, -32767, 32767}, {0, 1024}, {0, 0, 127}, {128, 255, 128}},
  {{32767, -32767, 32767}, {1024, 1024}, {0, 0, 127}, {128, 255, 128}},
  {{32767, 32767, 32767}, {1024, 0}, {0, 0, 127}, {128, 255, 128}},
  {{-32767, 32767, 32767}, {0, 0}, {0, 0, 127}, {128, 255, 128}},
  {{32767, -32767, -32767}, {0, 1024}, {0, 0, -127}, {128, 128, 255}},
  {{-32767, -32767, -32767}, {1024, 1024}, {0, 0, -127}, {128, 128, 255}},
  {{-32767, 32767, -32767}, {1024, 0}, {0, 0, -127}, {128, 128, 255}},
  {{32767, 32767, -32767}, {0, 0}, {0, 0, -127}, {128, 128, 255}},
};
static const g3::VertexBuffer mesh0Prim0Vb = {24, nullptr, mesh0Prim0Vertices, nullptr,
    {0.000015f, 0.000015f, 0.000015f}, {0.0f, 0.0f, 0.0f}};
static const uint16_t mesh0Prim0Indices[] = {
  0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8,
  10, 11, 12, 13, 14, 12, 14, 15, 16, 17, 18, 16, 18, 19, 20, 21,
  22, 20, 22, 23,
};

// texture: image 0 16x16 rgb565_swapped
alignas(4) static const uint16_t tex0Data[] = {
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0xD33A, 0xD33A, 0xD33A, 0xD33A, 0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
  0x3DE7, 0x3DE7, 0x3DE7, 0x3DE7, 0xD33A, 0xD33A, 0xD33A, 0xD33A,
};
static const shapoco::gfx2d::Texture tex0 = {
  shapoco::gfx2d::PixelFormat::RGB565_SWAPPED, 16, 16, 32, tex0Data,
};

static const g3::Material mat0Vc = {
  {1.0f, 1.0f, 1.0f, 1.0f}, {1.0f, 1.0f, 1.0f, 1.0f}, &tex0,
  g3::BlendMode::NONE, 0, 0, 0, g3::MaterialFlags::TEXTURE | g3::MaterialFlags::VERTEX_COLOR,
};

static const g3::Primitive mesh0Prims[] = {
  {g3::PrimitiveType::TRIANGLES, 0, 36, &mesh0Prim0Vb, mesh0Prim0Indices, &mat0Vc},
};
static const g3::Mesh mesh0 = {mesh0Prims, 1, 0};

// mesh 1 primitive 0: 5 vertices, 18 indices
static const g3::PackedVertex mesh1Prim0Vertices[] = {
  {{-32767, -32767, -32767}, {0, 0}, {-67, -84, -67}, {255, 255, 255}},
  {{32767, -32767, -32767}, {0, 0}, {90, 0, -90}, {255, 255, 255}},
  {{32767, -32767, 32767}, {0, 0}, {67, -84, 67}, {255, 255, 255}},
  {{-32767, -32767, 32767}, {0, 0}, {-90, 0, 90}, {255, 255, 255}},
  {{0, 32767, 0}, {0, 0}, {0, 127, 0}, {255, 255, 255}},
};
static const g3::VertexBuffer mesh1Prim0Vb = {5, nullptr, mesh1Prim0Vertices, nullptr,
    {0.000015f, 0.000012f, 0.000015f}, {0.0f, 0.4f, 0.0f}};
static const uint16_t mesh1Prim0Indices[] = {
  0, 4, 1, 1, 4, 2, 2, 4, 3, 3, 4, 0, 0, 1, 2, 0,
  2, 3,
};

static const g3::Material mat1 = {
  {0.9f, 0.2f, 0.1f, 1.0f}, {0.9f, 0.2f, 0.1f, 1.0f}, nullptr,
  g3::BlendMode::NONE, 0, 0, 0, g3::MaterialFlags::DOUBLE_SIDED,
};

static const g3::Primitive mesh1Prims[] = {
  {g3::PrimitiveType::TRIANGLES, 0, 18, &mesh1Prim0Vb, mesh1Prim0Indices, &mat1},
};
static const g3::Mesh mesh1 = {mesh1Prims, 1, 0};

// mesh 2 primitive 0: 6 vertices, 6 indices
static const g3::PackedVertex mesh2Prim0Vertices[] = {
  {{-32767, -32767, -32767}, {0, 0}, {0, 0, 0}, {255, 0, 0}},
  {{32767, -32767, -32767}, {0, 0}, {0, 0, 0}, {255, 0, 0}},
  {{-32767, -32767, -32767}, {0, 0}, {0, 0, 0}, {0, 255, 0}},
  {{-32767, 32767, -32767}, {0, 0}, {0, 0, 0}, {0, 255, 0}},
  {{-32767, -32767, -32767}, {0, 0}, {0, 0, 0}, {0, 0, 255}},
  {{-32767, -32767, 32767}, {0, 0}, {0, 0, 0}, {0, 0, 255}},
};
static const g3::VertexBuffer mesh2Prim0Vb = {6, nullptr, mesh2Prim0Vertices, nullptr,
    {0.000015f, 0.000015f, 0.000015f}, {0.5f, 0.5f, 0.5f}};
static const uint16_t mesh2Prim0Indices[] = {
  0, 1, 2, 3, 4, 5,
};

static const g3::Material matDefaultVc = {
  {1.0f, 1.0f, 1.0f, 1.0f}, {1.0f, 1.0f, 1.0f, 1.0f}, nullptr,
  g3::BlendMode::NONE, 0, 0, 0, g3::MaterialFlags::VERTEX_COLOR,
};

static const g3::Primitive mesh2Prims[] = {
  {g3::PrimitiveType::LINES, 0, 6, &mesh2Prim0Vb, mesh2Prim0Indices, &matDefaultVc},
};
static const g3::Mesh mesh2 = {mesh2Prims, 1, 0};

static const g3::NodeTRS node_CubeTrs = {{-0.8f, 0.0f, 0.0f}, {0.0f, 0.382683f, 0.0f, 0.92388f}, {1.0f, 1.0f, 1.0f}};
static const g3::Node node_Cube = {
  "Cube",
  {{0.707107f, 0.0f, -0.707107f, 0.0f,
    0.0f, 1.0f, 0.0f, 0.0f,
    0.707107f, 0.0f, 0.707107f, 0.0f,
    -0.8f, 0.0f, 0.0f, 1.0f}},
  &mesh0,
  nullptr, 0,
  0, &node_CubeTrs,  // flags (reserved), TRS
};

static const g3::NodeTRS node_Tip_PyramidTrs = {{0.0f, 0.9f, 0.0f}, {0.0f, 0.0f, 0.0f, 1.0f}, {0.4f, 0.4f, 0.4f}};
static const g3::Node node_Tip_Pyramid = {
  "Tip Pyramid",
  {{0.4f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.4f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.4f, 0.0f,
    0.0f, 0.9f, 0.0f, 1.0f}},
  &mesh1,
  nullptr, 0,
  0, &node_Tip_PyramidTrs,  // flags (reserved), TRS
};

static const g3::Node *const node_PyramidChildren[] = {&node_Tip_Pyramid};
static const g3::NodeTRS node_PyramidTrs = {{0.8f, -0.4f, 0.0f}, {0.0f, 0.0f, 0.0f, 1.0f}, {1.5f, 1.0f, 1.5f}};
static const g3::Node node_Pyramid = {
  "Pyramid",
  {{1.5f, 0.0f, 0.0f, 0.0f,
    0.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.5f, 0.0f,
    0.8f, -0.4f, 0.0f, 1.0f}},
  &mesh1,
  node_PyramidChildren, 1,
  0, &node_PyramidTrs,  // flags (reserved), TRS
};

static const g3::NodeTRS node_AxesTrs = {{0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 1.0f}, {1.5f, 1.5f, 1.5f}};
static const g3::Node node_Axes = {
  "Axes",
  {{1.5f, 0.0f, 0.0f, 0.0f,
    0.0f, 1.5f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.5f, 0.0f,
    0.0f, 0.0f, 0.0f, 1.0f}},
  &mesh2,
  nullptr, 0,
  0, &node_AxesTrs,  // flags (reserved), TRS
};

static const g3::Node *const node_RootChildren[] = {&node_Cube, &node_Pyramid, &node_Axes};
static const g3::NodeTRS node_RootTrs = {{0.0f, 0.2f, 0.0f}, {0.0f, 0.0f, 0.0f, 1.0f}, {1.0f, 1.0f, 1.0f}};
static const g3::Node node_Root = {
  "Root",
  {{1.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.0f, 0.0f,
    0.0f, 0.2f, 0.0f, 1.0f}},
  nullptr,
  node_RootChildren, 3,
  0, &node_RootTrs,  // flags (reserved), TRS
};

// All nodes in the order of the file (glTF node indices)
static const g3::Node *const nodes[] = {&node_Root, &node_Cube, &node_Pyramid, &node_Tip_Pyramid, &node_Axes};

static const g3::Node *const scene0Roots[] = {&node_Root};
static const g3::Scene scene0 = {scene0Roots, 1, 5, nodes};

static const g3::Scene &scene = scene0;  // default scene

// 35 vertices, 60 indices, 1 textures, about 1192 bytes

}  // namespace test_model_packed

#endif
