#ifndef TEST_VG_ANIM_TEST_VG_ANIM_HPP
#define TEST_VG_ANIM_TEST_VG_ANIM_HPP

// Generated by svg2cpp from test_vg_anim.svg
// rig: 13 bones, 8 slots, 12 shapes, 63 path ops, 0 images; animation main: 60 frames at 30 fps, 7 bone and 4 slot timelines, about 4235 bytes
// options: namespace test_vg_anim
// options: scale 1
// options: rig
// options: image-format argb4444
// options: dither none
// options: text-font nullptr
// options: fps 30
// options: duration 2.0
// options: anim-name main
// options: keep kept
// Group opacity is multiplied into the brushes of the descendants (which differs
// from SVG where they overlap).

#include "shapoco/gfx2d/rig.hpp"

static_assert(shapoco::gfx2d::vg::FORMAT_VERSION >= 1,
              "this header needs a newer ShapoGFX (vg.hpp FORMAT_VERSION)");
static_assert(shapoco::gfx2d::rig::FORMAT_VERSION >= 3,
              "this header needs a newer ShapoGFX (rig.hpp FORMAT_VERSION)");

namespace test_vg_anim {

static constexpr uint8_t OP_MOVE = (uint8_t)shapoco::gfx2d::vg::PathOp::MOVE;
static constexpr uint8_t OP_LINE = (uint8_t)shapoco::gfx2d::vg::PathOp::LINE;
static constexpr uint8_t OP_QUAD = (uint8_t)shapoco::gfx2d::vg::PathOp::QUAD;
static constexpr uint8_t OP_CUBIC = (uint8_t)shapoco::gfx2d::vg::PathOp::CUBIC;
static constexpr uint8_t OP_CLOSE = (uint8_t)shapoco::gfx2d::vg::PathOp::CLOSE;

static const uint8_t path_root_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_root_0Coords[] = {
  0.0f, 0.0f, 200.0f, 0.0f, 200.0f, 120.0f, 0.0f, 120.0f,
};
static const shapoco::gfx2d::vg::Path path_root_0 = {path_root_0Ops, path_root_0Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 0.0f, 200.0f, 120.0f}};

static const uint8_t path_root_1Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_root_1Coords[] = {
  0.0f, 0.0f, 30.0f, 0.0f, 30.0f, 10.0f, 0.0f, 10.0f,
};
static const shapoco::gfx2d::vg::Path path_root_1 = {path_root_1Ops, path_root_1Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 0.0f, 30.0f, 10.0f}};

static const uint8_t path_root_2Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_root_2Coords[] = {
  41.0f, 5.0f, 41.0f, 7.761424f, 38.76143f, 10.0f, 36.0f, 10.0f,
  33.23857f, 10.0f, 31.0f, 7.761424f, 31.0f, 5.0f, 31.0f, 2.238576f,
  33.23857f, 0.0f, 36.0f, 0.0f, 38.76143f, 0.0f, 41.0f, 2.238576f,
  41.0f, 5.0f,
};
static const shapoco::gfx2d::vg::Path path_root_2 = {path_root_2Ops, path_root_2Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {31.0f, 0.0f, 10.0f, 10.0f}};

static const shapoco::gfx2d::vg::Shape shapes_root[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_root_0, {0xFFEEEEEEu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_root_1, {0xFFBBBBBBu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 4.0f, 4.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_root_2, {0xFF999999u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 4.0f, 4.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_root = {shapes_root, 3, 0, {0.0f, 0.0f, 200.0f, 120.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_root[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_root},
};

static const uint8_t path_wheel_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_wheel_0Coords[] = {
  24.0f, 0.0f, 24.0f, 13.25483f, 13.25483f, 24.0f, 0.0f, 24.0f,
  -13.25483f, 24.0f, -24.0f, 13.25483f, -24.0f, 0.0f, -24.0f, -13.25483f,
  -13.25483f, -24.0f, 0.0f, -24.0f, 13.25483f, -24.0f, 24.0f, -13.25483f,
  24.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_wheel_0 = {path_wheel_0Ops, path_wheel_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-24.0f, -24.0f, 48.0f, 48.0f}};

static const shapoco::gfx2d::vg::GradientStop stops_wheel_0[] = {
  {0.0f, 0xFFFFD700u},
  {1.0f, 0xFFDC143Cu},
};
static const shapoco::gfx2d::vg::Gradient gradient_wheel_0 = {shapoco::gfx2d::vg::GradientKind::LINEAR, shapoco::gfx2d::vg::Spread::PAD, 2, 0, stops_wheel_0, {0.02083333f, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f}};

static const uint8_t path_wheel_1Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_wheel_1Coords[] = {
  -2.0f, -24.0f, 2.0f, -24.0f, 2.0f, 24.0f, -2.0f, 24.0f,
};
static const shapoco::gfx2d::vg::Path path_wheel_1 = {path_wheel_1Ops, path_wheel_1Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-2.0f, -24.0f, 4.0f, 48.0f}};

static const shapoco::gfx2d::vg::Shape shapes_wheel[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_wheel_0, {0xFF000000u, &gradient_wheel_0}, {0xFF333333u, nullptr}, {2.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_wheel_1, {0xFF333333u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_wheel = {shapes_wheel, 2, 0, {-25.0f, -25.0f, 50.0f, 50.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_wheel[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_wheel},
};

static const uint8_t path_kept_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_kept_0Coords[] = {
  0.0f, 0.0f, 20.0f, 0.0f, 20.0f, 12.0f, 0.0f, 12.0f,
};
static const shapoco::gfx2d::vg::Path path_kept_0 = {path_kept_0Ops, path_kept_0Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 0.0f, 20.0f, 12.0f}};

static const shapoco::gfx2d::vg::Shape shapes_kept[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_kept_0, {0xFF3366CCu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_kept = {shapes_kept, 1, 0, {0.0f, 0.0f, 20.0f, 12.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_kept[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_kept},
};

static const uint8_t path_fader_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_fader_0Coords[] = {
  80.0f, 30.0f, 110.0f, 30.0f, 110.0f, 42.0f, 80.0f, 42.0f,
};
static const shapoco::gfx2d::vg::Path path_fader_0 = {path_fader_0Ops, path_fader_0Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {80.0f, 30.0f, 30.0f, 12.0f}};

static const shapoco::gfx2d::vg::Shape shapes_fader[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 1, {0, 0}, &path_fader_0, {0xFFCC3366u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_fader = {shapes_fader, 1, 0, {80.0f, 30.0f, 30.0f, 12.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_fader[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_fader},
};

static const uint8_t path_blob_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_blob_0Coords[] = {
  8.0f, 0.0f, 8.0f, 4.418278f, 4.418278f, 8.0f, 0.0f, 8.0f,
  -4.418278f, 8.0f, -8.0f, 4.418278f, -8.0f, 0.0f, -8.0f, -4.418278f,
  -4.418278f, -8.0f, 0.0f, -8.0f, 4.418278f, -8.0f, 8.0f, -4.418278f,
  8.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_blob_0 = {path_blob_0Ops, path_blob_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-8.0f, -8.0f, 16.0f, 16.0f}};

static const shapoco::gfx2d::vg::Shape shapes_blob[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 4, {0, 0}, &path_blob_0, {0xFF008000u, nullptr}, {0xFF000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_blob = {shapes_blob, 1, 0, {-8.5f, -8.5f, 17.0f, 17.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_blob[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_blob},
};

static const uint8_t path_arrow_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_arrow_0Coords[] = {
  0.0f, -4.0f, 8.0f, 0.0f, 0.0f, 4.0f,
};
static const shapoco::gfx2d::vg::Path path_arrow_0 = {path_arrow_0Ops, path_arrow_0Coords, 4, 6, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, -4.0f, 8.0f, 8.0f}};

static const shapoco::gfx2d::vg::Shape shapes_arrow[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_arrow_0, {0xFFFF6600u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_arrow = {shapes_arrow, 1, 0, {0.0f, -4.0f, 8.0f, 8.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_arrow[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_arrow},
};

static const uint8_t path_blinker_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_blinker_0Coords[] = {
  170.0f, 100.0f, 190.0f, 100.0f, 190.0f, 112.0f, 170.0f, 112.0f,
};
static const shapoco::gfx2d::vg::Path path_blinker_0 = {path_blinker_0Ops, path_blinker_0Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {170.0f, 100.0f, 20.0f, 12.0f}};

static const shapoco::gfx2d::vg::Shape shapes_blinker[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_blinker_0, {0xFF660066u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_blinker = {shapes_blinker, 1, 0, {170.0f, 100.0f, 20.0f, 12.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_blinker[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_blinker},
};

static const uint8_t path_spin_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path_spin_0Coords[] = {
  -10.0f, -5.0f, 10.0f, -5.0f, 10.0f, 5.0f, -10.0f, 5.0f,
};
static const shapoco::gfx2d::vg::Path path_spin_0 = {path_spin_0Ops, path_spin_0Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-10.0f, -5.0f, 20.0f, 10.0f}};

static const uint8_t path_spin_1Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_spin_1Coords[] = {
  15.0f, 0.0f, 15.0f, 1.656854f, 13.65685f, 3.0f, 12.0f, 3.0f,
  10.34315f, 3.0f, 9.0f, 1.656854f, 9.0f, 0.0f, 9.0f, -1.656854f,
  10.34315f, -3.0f, 12.0f, -3.0f, 13.65685f, -3.0f, 15.0f, -1.656854f,
  15.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_spin_1 = {path_spin_1Ops, path_spin_1Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {9.0f, -3.0f, 6.0f, 6.0f}};

static const shapoco::gfx2d::vg::Shape shapes_spin[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_spin_0, {0xFF006699u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, -5.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_spin_1, {0xFF0099CCu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, -5.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_spin = {shapes_spin, 2, 0, {-15.0f, -5.0f, 25.0f, 10.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_spin[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_spin},
};

static const shapoco::gfx2d::rig::Bone bones[] = {
  {"root", 0.0f, 0.0f, 0, 0, 4096, 4096, 0xFF, 0},
  {"wheel_base", 40.0f, 60.0f, 0, 0, 4096, 4096, 0, 0},
  {"wheel", 0.0f, 0.0f, 0, 0, 4096, 4096, 1, 0},
  {"slider_base", 80.0f, 10.0f, 0, 0, 4096, 4096, 0, 0},
  {"slider", 0.0f, 0.0f, 0, 0, 4096, 4096, 3, 0},
  {"kept", 0.0f, 0.0f, 0, 0, 4096, 4096, 4, 0},
  {"fader", 0.0f, 0.0f, 0, 0, 4096, 4096, 0, 0},
  {"blob", 100.0f, 80.0f, 0, 0, 4096, 4096, 0, 0},
  {"arrow", 0.0f, 0.0f, 0, 0, 4096, 4096, 0, 0},
  {"blinker", 0.0f, 0.0f, 0, 0, 4096, 4096, 0, 0},
  {"spin_base", 150.0f, 60.0f, 0, 0, 4096, 4096, 0, 0},
  {"spin_pivot", 5.0f, 0.0f, 0, 0, 4096, 4096, 10, 0},
  {"spin", 0.0f, 0.0f, 0, 0, 4096, 4096, 11, 0},
};

static const shapoco::gfx2d::rig::Slot slots[] = {
  {"root", attachments_root, 1, 0, 0, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"wheel", attachments_wheel, 1, 0, 2, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"kept", attachments_kept, 1, 0, 5, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"fader", attachments_fader, 1, 0, 6, 255, shapoco::gfx2d::BlendMode::ALPHA, 204, 51, 102, nullptr, 0, {0, 0, 0}, 0.0f},
  {"blob", attachments_blob, 1, 0, 7, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 1.0f},
  {"arrow", attachments_arrow, 1, 0, 8, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"blinker", attachments_blinker, 1, 0, 9, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"spin", attachments_spin, 1, 0, 12, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
};

static const shapoco::gfx2d::rig::Armature armature = {
  "root", bones, slots, 13, 8,
  false, 0x00000000u,
  {0.0f, 0.0f, 200.0f, 120.0f},
  0xF8B3326Au,
  shapoco::gfx2d::rig::FEATURE_SLOT_COLOR | shapoco::gfx2d::rig::FEATURE_STROKE_WIDTH,
};

// animation "main": 60 frames at 30 fps
static const shapoco::gfx2d::rig::Curve anim_main_curves[] = {
  {{0, 113, 426, 906, 1531, 2283, 3146, 4110, 5167, 6308, 7528, 8822, 10189, 11624, 13130, 14711, 16384}},
  {{0, 1673, 3254, 4760, 6195, 7562, 8856, 10076, 11217, 12274, 13238, 14101, 14853, 15478, 15958, 16271, 16384}},
};
static const shapoco::gfx2d::rig::RotateKey anim_main_bone2_rotate[] = {
  {0, 0xFF, 0, 0, 0},
  {15, 0xFF, 0, 16384, 16384},
  {30, 0xFF, 0, -32768, -32768},
  {45, 0xFF, 0, -16384, -16384},
  {60, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone4_translate[] = {
  {0, 0xFF, 0, 0.0f, 0.0f},
  {15, 0xFF, 0, 60.0f, 0.0f},
  {30, 0xFF, 0, 0.0f, 0.0f},
  {45, 0xFF, 0, 60.0f, 0.0f},
  {60, 0xFE, 0, 0.0f, 0.0f},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone7_translate[] = {
  {0, 0xFF, 0, 0.0f, 0.0f},
  {30, 0xFE, 0, 60.0f, 0.0f},
  {30, 0xFF, 0, 0.0f, 0.0f},
  {60, 0xFE, 0, 60.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone7_scale[] = {
  {0, 0xFE, 0, 4096, 4096},
  {15, 0xFF, 0, 4096, 4096},
  {45, 0xFE, 0, 8192, 8192},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone8_translate[] = {
  {0, 0xFF, 0, 0.0f, 0.0f},
  {13, 0xFF, 0, 39.61f, 0.0f},
  {14, 0xFF, 0, 42.64735f, 0.1952042f},
  {15, 0xFF, 0, 45.62635f, 0.8166123f},
  {16, 0xFF, 0, 48.46844f, 1.900977f},
  {17, 0xFF, 0, 51.12717f, 3.382259f},
  {18, 0xFF, 0, 53.50628f, 5.279963f},
  {19, 0xFF, 0, 55.59375f, 7.49314f},
  {20, 0xFF, 0, 57.3075f, 10.0082f},
  {21, 0xFF, 0, 58.62413f, 12.75013f},
  {22, 0xFF, 0, 59.51421f, 15.66026f},
  {23, 0xFF, 0, 59.933f, 18.67323f},
  {24, 0xFF, 0, 59.91333f, 21.71627f},
  {25, 0xFF, 0, 59.41709f, 24.71745f},
  {26, 0xFF, 0, 58.49008f, 27.6161f},
  {27, 0xFF, 0, 57.105f, 30.32511f},
  {28, 0xFF, 0, 55.35123f, 32.8118f},
  {29, 0xFF, 0, 53.21768f, 34.98234f},
  {30, 0xFF, 0, 50.79386f, 36.82023f},
  {31, 0xFF, 0, 48.11709f, 38.26828f},
  {32, 0xFF, 0, 45.24864f, 39.28051f},
  {33, 0xFF, 0, 42.26181f, 39.86364f},
  {34, 0xFF, 0, 39.22001f, 40.0f},
  {46, 0xFF, 0, 2.656926f, 40.0f},
  {47, 0xFF, 0, 0.0f, 39.61f},
  {60, 0xFE, 0, 0.0f, 0.0f},
};
static const shapoco::gfx2d::rig::RotateKey anim_main_bone8_rotate[] = {
  {0, 0xFE, 0, 0, 0},
  {13, 0xFF, 0, 0, 0},
  {14, 0xFF, 0, 1580, 1580},
  {15, 0xFF, 0, 2625, 2625},
  {16, 0xFF, 0, 4682, 4682},
  {17, 0xFF, 0, 5694, 5694},
  {18, 0xFF, 0, 7694, 7694},
  {19, 0xFF, 0, 9687, 9687},
  {20, 0xFF, 0, 10690, 10690},
  {21, 0xFF, 0, 12724, 12724},
  {22, 0xFF, 0, 13759, 13759},
  {23, 0xFF, 0, 15858, 15858},
  {24, 0xFF, 0, 16910, 16910},
  {25, 0xFF, 0, 19009, 19009},
  {26, 0xFF, 0, 20044, 20044},
  {27, 0xFF, 0, 22078, 22078},
  {28, 0xFF, 0, 24078, 24078},
  {29, 0xFF, 0, 25074, 25074},
  {30, 0xFF, 0, 27074, 27074},
  {31, 0xFF, 0, 28086, 28086},
  {32, 0xFF, 0, 30143, 30143},
  {33, 0xFF, 0, 31188, 31188},
  {34, 0xFE, 0, -32768, -32768},
  {46, 0xFF, 0, -32768, -32768},
  {47, 0xFE, 0, -16384, -16384},
};
static const shapoco::gfx2d::rig::RotateKey anim_main_bone12_rotate[] = {
  {0, 0xFF, 0, 0, 0},
  {30, 0xFF, 0, 16384, 16384},
  {60, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot3_alpha[] = {
  {0, 0x00, 255},
  {24, 0x01, 26},
  {60, 0xFE, 255},
};
static const shapoco::gfx2d::rig::ColorKey anim_main_slot3_color[] = {
  {0, 0xFF, 204, 51, 102, {0, 0}},
  {60, 0xFE, 51, 204, 102, {0, 0}},
};
static const shapoco::gfx2d::rig::StrokeWidthKey anim_main_slot4_stroke_width[] = {
  {0, 0xFF, 0, 1.0f},
  {15, 0xFE, 0, 2.0f},
  {30, 0xFE, 0, 2.0f},
  {30, 0xFF, 0, 0.6666667f},
  {31, 0xFF, 0, 0.6956522f},
  {32, 0xFF, 0, 0.7234042f},
  {33, 0xFF, 0, 0.75f},
  {34, 0xFF, 0, 0.7755102f},
  {35, 0xFF, 0, 0.8f},
  {36, 0xFF, 0, 0.8235294f},
  {37, 0xFF, 0, 0.8461539f},
  {38, 0xFF, 0, 0.8679245f},
  {39, 0xFF, 0, 0.8888889f},
  {40, 0xFF, 0, 0.9090909f},
  {41, 0xFF, 0, 0.9285714f},
  {42, 0xFF, 0, 0.9473684f},
  {43, 0xFF, 0, 0.9655172f},
  {44, 0xFF, 0, 0.9830508f},
  {45, 0xFF, 0, 1.0f},
  {60, 0xFE, 0, 1.5f},
};
static const shapoco::gfx2d::rig::AttachmentKey anim_main_slot6_attachment[] = {
  {0, 0, 0},
  {15, -1, 0},
  {30, 0, 0},
};
static const shapoco::gfx2d::rig::BoneTimeline anim_main_boneTimelines[] = {
  {anim_main_bone2_rotate, 5, 2, shapoco::gfx2d::rig::Channel::ROTATE},
  {anim_main_bone4_translate, 5, 4, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone7_translate, 4, 7, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone7_scale, 3, 7, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone8_translate, 26, 8, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone8_rotate, 25, 8, shapoco::gfx2d::rig::Channel::ROTATE},
  {anim_main_bone12_rotate, 3, 12, shapoco::gfx2d::rig::Channel::ROTATE},
};
static const shapoco::gfx2d::rig::SlotTimeline anim_main_slotTimelines[] = {
  {anim_main_slot3_alpha, 3, 3, shapoco::gfx2d::rig::Channel::ALPHA},
  {anim_main_slot3_color, 2, 3, shapoco::gfx2d::rig::Channel::COLOR},
  {anim_main_slot4_stroke_width, 20, 4, shapoco::gfx2d::rig::Channel::STROKE_WIDTH},
  {anim_main_slot6_attachment, 3, 6, shapoco::gfx2d::rig::Channel::ATTACHMENT},
};
static const shapoco::gfx2d::rig::Animation anim_main = {
  "main", 60, 30, 7, 4, 2, 0,
  anim_main_boneTimelines, anim_main_slotTimelines, nullptr, anim_main_curves,
  0xF8B3326Au,
  shapoco::gfx2d::rig::FEATURE_SLOT_COLOR | shapoco::gfx2d::rig::FEATURE_STROKE_WIDTH,
};

static const shapoco::gfx2d::rig::Animation *const animations[] = {&anim_main};
static constexpr int ANIMATION_COUNT = 1;

}  // namespace test_vg_anim

#endif
