#ifndef TEST_VG_TEST_VG_HPP
#define TEST_VG_TEST_VG_HPP

// Generated by svg2cpp from test_vg.svg
// picture: 19 shapes, 120 path ops, 2 gradients, 1 images, 2 bitmap texts, about 3508 bytes
// options: namespace test_vg
// options: scale 1
// options: picture
// options: image-format argb4444
// options: dither none
// options: text-font nullptr
// Group opacity is multiplied into the brushes of the descendants (which differs
// from SVG where they overlap).
// 2 warning(s):
//   <text id=label>: no font for 'sans-serif', emitted as a vg::Text drawn with the bitmap font
//   <text id=anchored>: no font for 'sans-serif', emitted as a vg::Text drawn with the bitmap font (text-anchor end cannot be applied)

#include "shapoco/gfx2d/vg.hpp"

static_assert(shapoco::gfx2d::vg::FORMAT_VERSION >= 1,
              "this header needs a newer ShapoGFX (vg.hpp FORMAT_VERSION)");

namespace test_vg {

static constexpr uint8_t OP_MOVE = (uint8_t)shapoco::gfx2d::vg::PathOp::MOVE;
static constexpr uint8_t OP_LINE = (uint8_t)shapoco::gfx2d::vg::PathOp::LINE;
static constexpr uint8_t OP_QUAD = (uint8_t)shapoco::gfx2d::vg::PathOp::QUAD;
static constexpr uint8_t OP_CUBIC = (uint8_t)shapoco::gfx2d::vg::PathOp::CUBIC;
static constexpr uint8_t OP_CLOSE = (uint8_t)shapoco::gfx2d::vg::PathOp::CLOSE;

static const uint8_t path0Ops[] = {
  OP_MOVE, OP_LINE, OP_CUBIC, OP_LINE, OP_CUBIC, OP_LINE, OP_CUBIC, OP_LINE, OP_CUBIC, OP_CLOSE,
};
static const float path0Coords[] = {
  14.0f, 8.0f, 42.0f, 8.0f, 45.31371f, 8.0f, 48.0f, 9.790861f,
  48.0f, 12.0f, 48.0f, 28.0f, 48.0f, 30.20914f, 45.31371f, 32.0f,
  42.0f, 32.0f, 14.0f, 32.0f, 10.68629f, 32.0f, 8.0f, 30.20914f,
  8.0f, 28.0f, 8.0f, 12.0f, 8.0f, 9.790861f, 10.68629f, 8.0f,
  14.0f, 8.0f,
};
static const shapoco::gfx2d::vg::Path path0 = {path0Ops, path0Coords, 10, 34, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {8.0f, 8.0f, 40.0f, 24.0f}};

static const uint8_t path1Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path1Coords[] = {
  92.0f, 20.0f, 92.0f, 26.62742f, 86.62742f, 32.0f, 80.0f, 32.0f,
  73.37258f, 32.0f, 68.0f, 26.62742f, 68.0f, 20.0f, 68.0f, 13.37258f,
  73.37258f, 8.0f, 80.0f, 8.0f, 86.62742f, 8.0f, 92.0f, 13.37258f,
  92.0f, 20.0f,
};
static const shapoco::gfx2d::vg::Path path1 = {path1Ops, path1Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {68.0f, 8.0f, 24.0f, 24.0f}};

static const shapoco::gfx2d::vg::GradientStop stops1[] = {
  {0.0f, 0xFFFF0000u},
  {0.5f, 0x8000FF00u},
  {1.0f, 0xFF0000FFu},
};
static const shapoco::gfx2d::vg::Gradient gradient1 = {shapoco::gfx2d::vg::GradientKind::LINEAR, shapoco::gfx2d::vg::Spread::PAD, 3, 0, stops1, {0.02083333f, 0.0f, 0.02083333f, 0.0f, -1.583333f, 0.0f}};

static const uint8_t path2Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path2Coords[] = {
  144.0f, 30.0f, 144.0f, 37.73199f, 133.2548f, 44.0f, 120.0f, 44.0f,
  106.7452f, 44.0f, 96.0f, 37.73199f, 96.0f, 30.0f, 96.0f, 22.26801f,
  106.7452f, 16.0f, 120.0f, 16.0f, 133.2548f, 16.0f, 144.0f, 22.26801f,
  144.0f, 30.0f,
};
static const shapoco::gfx2d::vg::Path path2 = {path2Ops, path2Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {96.0f, 16.0f, 48.0f, 28.0f}};

static const shapoco::gfx2d::vg::GradientStop stops2[] = {
  {0.0f, 0xFFFFFFFFu},
  {1.0f, 0xFF000000u},
};
static const shapoco::gfx2d::vg::Gradient gradient2 = {shapoco::gfx2d::vg::GradientKind::RADIAL, shapoco::gfx2d::vg::Spread::REFLECT, 2, 0, stops2, {0.05f, 0.0f, 0.0f, 0.1f, -6.0f, -3.0f}};

static const uint8_t path3Ops[] = {
  OP_MOVE, OP_LINE, OP_MOVE, OP_LINE, OP_MOVE, OP_LINE, OP_MOVE, OP_LINE, OP_MOVE, OP_LINE,
  OP_MOVE, OP_LINE, OP_MOVE, OP_LINE, OP_MOVE, OP_LINE,
};
static const float path3Coords[] = {
  8.0f, 40.0f, 12.0f, 40.0f, 15.0f, 40.0f, 17.0f, 40.0f,
  20.0f, 40.0f, 26.0f, 40.0f, 29.0f, 40.0f, 31.0f, 40.0f,
  34.0f, 40.0f, 40.0f, 40.0f, 43.0f, 40.0f, 45.0f, 40.0f,
  48.0f, 40.0f, 54.0f, 40.0f, 57.0f, 40.0f, 59.0f, 40.0f,
};
static const shapoco::gfx2d::vg::Path path3 = {path3Ops, path3Coords, 16, 32, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {8.0f, 40.0f, 51.0f, 0.0f}};

static const uint8_t path4Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
};
static const float path4Coords[] = {
  64.0f, 40.0f, 72.0f, 48.0f, 80.0f, 40.0f, 88.0f, 48.0f,
  96.0f, 40.0f,
};
static const shapoco::gfx2d::vg::Path path4 = {path4Ops, path4Coords, 5, 10, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {64.0f, 40.0f, 32.0f, 8.0f}};

static const uint8_t path5Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path5Coords[] = {
  104.0f, 40.0f, 120.0f, 56.0f, 136.0f, 40.0f,
};
static const shapoco::gfx2d::vg::Path path5 = {path5Ops, path5Coords, 4, 6, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {104.0f, 40.0f, 32.0f, 16.0f}};

static const uint8_t path6Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_CUBIC, OP_CUBIC, OP_CUBIC,
  OP_CUBIC, OP_QUAD, OP_QUAD, OP_QUAD, OP_QUAD, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
  OP_MOVE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path6Coords[] = {
  8.0f, 100.0f, 28.0f, 100.0f, 28.0f, 90.0f, 40.0f, 90.0f,
  40.0f, 100.0f, 44.0f, 92.0f, 50.0f, 100.0f, 52.0f, 94.0f,
  56.0f, 94.0f, 58.0f, 100.0f, 60.0f, 110.0f, 66.0f, 110.0f,
  68.0f, 100.0f, 70.0f, 90.0f, 74.0f, 94.0f, 76.0f, 100.0f,
  78.0f, 106.0f, 86.0f, 110.0f, 88.0f, 100.0f, 92.0f, 92.0f,
  96.0f, 100.0f, 100.0f, 110.0f, 104.0f, 100.0f, 108.0f, 90.0f,
  112.0f, 100.0f, 116.0f, 110.0f, 120.0f, 100.0f, 120.0f, 96.68629f,
  122.6863f, 94.0f, 126.0f, 94.0f, 129.3137f, 94.0f, 132.0f, 96.68629f,
  132.0f, 100.0f, 132.0f, 103.3137f, 134.6863f, 106.0f, 138.0f, 106.0f,
  141.3137f, 106.0f, 144.0f, 103.3137f, 144.0f, 100.0f, 10.0f, 70.0f,
  16.0f, 70.0f, 13.0f, 76.0f,
};
static const shapoco::gfx2d::vg::Path path6 = {path6Ops, path6Coords, 24, 84, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {8.0f, 70.0f, 136.0f, 40.0f}};

static const uint8_t path7Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path7Coords[] = {
  0.0f, 0.0f, 20.0f, 0.0f, 20.0f, 12.0f, 0.0f, 12.0f,
};
static const shapoco::gfx2d::vg::Path path7 = {path7Ops, path7Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 0.0f, 20.0f, 12.0f}};

static const uint8_t path8Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path8Coords[] = {
  31.0f, 6.0f, 31.0f, 8.761424f, 28.76142f, 11.0f, 26.0f, 11.0f,
  23.23858f, 11.0f, 21.0f, 8.761424f, 21.0f, 6.0f, 21.0f, 3.238576f,
  23.23858f, 1.0f, 26.0f, 1.0f, 28.76142f, 1.0f, 31.0f, 3.238576f,
  31.0f, 6.0f,
};
static const shapoco::gfx2d::vg::Path path8 = {path8Ops, path8Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {21.0f, 1.0f, 10.0f, 10.0f}};

static const uint8_t path9Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path9Coords[] = {
  0.0f, 60.0f, 60.0f, 60.0f, 60.0f, 100.0f, 0.0f, 100.0f,
};
static const shapoco::gfx2d::vg::Path path9 = {path9Ops, path9Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 60.0f, 60.0f, 40.0f}};
static const shapoco::gfx2d::RectF clip9 = {8.0f, 64.0f, 40.0f, 30.0f};

static const uint8_t path10Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path10Coords[] = {
  44.0f, 80.0f, 44.0f, 87.73199f, 37.73199f, 94.0f, 30.0f, 94.0f,
  22.26801f, 94.0f, 16.0f, 87.73199f, 16.0f, 80.0f, 16.0f, 72.26801f,
  22.26801f, 66.0f, 30.0f, 66.0f, 37.73199f, 66.0f, 44.0f, 72.26801f,
  44.0f, 80.0f,
};
static const shapoco::gfx2d::vg::Path path10 = {path10Ops, path10Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {16.0f, 66.0f, 28.0f, 28.0f}};
static const shapoco::gfx2d::RectF clip10 = {8.0f, 64.0f, 40.0f, 30.0f};

static const uint8_t path11Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path11Coords[] = {
  3.0f, 0.0f, 3.0f, 1.656854f, 1.656854f, 3.0f, 0.0f, 3.0f,
  -1.656854f, 3.0f, -3.0f, 1.656854f, -3.0f, 0.0f, -3.0f, -1.656854f,
  -1.656854f, -3.0f, 0.0f, -3.0f, 1.656854f, -3.0f, 3.0f, -1.656854f,
  3.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path11 = {path11Ops, path11Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.0f, -3.0f, 6.0f, 6.0f}};

static const uint8_t path12Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path12Coords[] = {
  3.0f, 0.0f, 3.0f, 1.656854f, 1.656854f, 3.0f, 0.0f, 3.0f,
  -1.656854f, 3.0f, -3.0f, 1.656854f, -3.0f, 0.0f, -3.0f, -1.656854f,
  -1.656854f, -3.0f, 0.0f, -3.0f, 1.656854f, -3.0f, 3.0f, -1.656854f,
  3.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path12 = {path12Ops, path12Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.0f, -3.0f, 6.0f, 6.0f}};

alignas(4) static const uint16_t img0Data[] = {
  0xF2C0, 0x85C4, 0xF8C8, 0x8BCC, 0x8285, 0xF589, 0x888E, 0xFB83,
  0xF25B, 0x855F, 0xF854, 0x8B58,
};
static const shapoco::gfx2d::Texture img0 = {
  shapoco::gfx2d::PixelFormat::ARGB4444, 4, 3, 8, img0Data,
};

static const shapoco::gfx2d::vg::Text text15 = {"Hi, vg!", nullptr, 120.0f, 110.0f};

static const shapoco::gfx2d::vg::Text text16 = {"end", nullptr, 150.0f, 80.0f};

static const uint8_t path17Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE, OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path17Coords[] = {
  120.0f, 60.0f, 150.0f, 60.0f, 150.0f, 80.0f, 120.0f, 80.0f,
  128.0f, 66.0f, 142.0f, 66.0f, 142.0f, 74.0f, 128.0f, 74.0f,
};
static const shapoco::gfx2d::vg::Path path17 = {path17Ops, path17Coords, 10, 16, shapoco::gfx2d::vg::FillRule::EVEN_ODD, {0, 0, 0}, {120.0f, 60.0f, 30.0f, 20.0f}};

static const uint8_t path18Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_CLOSE,
};
static const float path18Coords[] = {
  0.0f, 0.0f, 4.0f, 0.0f, 4.0f, 4.0f, 0.0f, 4.0f,
};
static const shapoco::gfx2d::vg::Path path18 = {path18Ops, path18Coords, 5, 8, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {0.0f, 0.0f, 4.0f, 4.0f}};

static const shapoco::gfx2d::vg::Shape shapes[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path0, {0xFFFFCC00u, nullptr}, {0xFF333333u, nullptr}, {2.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path1, {0xFF000000u, &gradient1}, {0xFF000080u, nullptr}, {3.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path2, {0xFF000000u, &gradient2}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path3, {0x00000000u, nullptr}, {0xFF000000u, nullptr}, {2.0f, shapoco::gfx2d::vg::LineCap::ROUND, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path4, {0x00000000u, nullptr}, {0xFF006400u, nullptr}, {3.0f, shapoco::gfx2d::vg::LineCap::SQUARE, shapoco::gfx2d::vg::LineJoin::BEVEL, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path5, {0xFFFF8000u, nullptr}, {0xFFA52A2Au, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 2.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path6, {0xFFC0C0FFu, nullptr}, {0xBF000080u, nullptr}, {1.5f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path7, {0x80FFCC00u, nullptr}, {0x80333333u, nullptr}, {2.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.082532f, 0.625f, -0.1099365f, 0.8602886f, 108.175f, 60.17061f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 3, {0, 0}, &path8, {0x80800080u, nullptr}, {0x80800080u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.082532f, 0.625f, -0.1099365f, 0.8602886f, 108.175f, 60.17061f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path9, {0xFF008080u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, &clip9},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path10, {0x80FFA500u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, &clip10},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path11, {0xFFFF00FFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 70.0f, 80.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path12, {0xFFFF00FFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 78.0f, 80.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::IMAGE, 0, {0, 0}, &img0, {0xFF000000u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {6.0f, 0.0f, 0.0f, 6.0f, 60.0f, 90.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::IMAGE, 0, {0, 0}, &img0, {0x80000000u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {6.0f, 0.0f, 0.0f, 6.0f, 88.0f, 90.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::TEXT, 0, {0, 0}, &text15, {0xFF202020u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::TEXT, 0, {0, 0}, &text16, {0xFF000000u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path17, {0xFF008080u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path18, {0xFF123456u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture = {shapes, 19, 0, {0.0f, 0.0f, 160.0f, 120.0f}};

}  // namespace test_vg

#endif
