#ifndef POP_STAR_POP_STAR_HPP
#define POP_STAR_POP_STAR_HPP

// Generated by svg2cpp from pop_star.svg
// rig: 22 bones, 10 slots, 11 shapes, 91 path ops, 0 images; animation main: 45 frames at 30 fps, 15 bone and 6 slot timelines, about 4901 bytes
// options: namespace pop_star
// options: scale 1
// options: rig
// options: image-format argb4444
// options: dither none
// options: text-font nullptr
// options: fps 30
// options: duration auto
// options: anim-name main
// Group opacity is multiplied into the brushes of the descendants (which differs
// from SVG where they overlap).

#include "shapoco/gfx2d/rig.hpp"

static_assert(shapoco::gfx2d::vg::FORMAT_VERSION >= 1,
              "this header needs a newer ShapoGFX (vg.hpp FORMAT_VERSION)");
static_assert(shapoco::gfx2d::rig::FORMAT_VERSION >= 3,
              "this header needs a newer ShapoGFX (rig.hpp FORMAT_VERSION)");

namespace pop_star {

static constexpr uint8_t OP_MOVE = (uint8_t)shapoco::gfx2d::vg::PathOp::MOVE;
static constexpr uint8_t OP_LINE = (uint8_t)shapoco::gfx2d::vg::PathOp::LINE;
static constexpr uint8_t OP_QUAD = (uint8_t)shapoco::gfx2d::vg::PathOp::QUAD;
static constexpr uint8_t OP_CUBIC = (uint8_t)shapoco::gfx2d::vg::PathOp::CUBIC;
static constexpr uint8_t OP_CLOSE = (uint8_t)shapoco::gfx2d::vg::PathOp::CLOSE;

static const uint8_t path_circle1_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_circle1_0Coords[] = {
  6.0f, 0.0f, 6.0f, 3.313709f, 3.313709f, 6.0f, 0.0f, 6.0f,
  -3.313709f, 6.0f, -6.0f, 3.313709f, -6.0f, 0.0f, -6.0f, -3.313709f,
  -3.313709f, -6.0f, 0.0f, -6.0f, 3.313709f, -6.0f, 6.0f, -3.313709f,
  6.0f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_circle1_0 = {path_circle1_0Ops, path_circle1_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-6.0f, -6.0f, 12.0f, 12.0f}};

static const shapoco::gfx2d::vg::Shape shapes_circle1[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 4, {0, 0}, &path_circle1_0, {0x00000000u, nullptr}, {0xFFFFB3D1u, nullptr}, {0.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_circle1 = {shapes_circle1, 1, 0, {-6.0f, -6.0f, 12.0f, 12.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_circle1[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_circle1},
};

static const uint8_t path_circle2_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_circle2_0Coords[] = {
  3.5f, 0.0f, 3.5f, 1.932997f, 1.932997f, 3.5f, 0.0f, 3.5f,
  -1.932997f, 3.5f, -3.5f, 1.932997f, -3.5f, 0.0f, -3.5f, -1.932997f,
  -1.932997f, -3.5f, 0.0f, -3.5f, 1.932997f, -3.5f, 3.5f, -1.932997f,
  3.5f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_circle2_0 = {path_circle2_0Ops, path_circle2_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::vg::Shape shapes_circle2[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_circle2_0, {0xFFA8D8FFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_circle2 = {shapes_circle2, 1, 0, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_circle2[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_circle2},
};

static const uint8_t path_circle3_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_circle3_0Coords[] = {
  3.5f, 0.0f, 3.5f, 1.932997f, 1.932997f, 3.5f, 0.0f, 3.5f,
  -1.932997f, 3.5f, -3.5f, 1.932997f, -3.5f, 0.0f, -3.5f, -1.932997f,
  -1.932997f, -3.5f, 0.0f, -3.5f, 1.932997f, -3.5f, 3.5f, -1.932997f,
  3.5f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_circle3_0 = {path_circle3_0Ops, path_circle3_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::vg::Shape shapes_circle3[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_circle3_0, {0xFFA8EED5u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_circle3 = {shapes_circle3, 1, 0, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_circle3[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_circle3},
};

static const uint8_t path_circle4_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_circle4_0Coords[] = {
  3.5f, 0.0f, 3.5f, 1.932997f, 1.932997f, 3.5f, 0.0f, 3.5f,
  -1.932997f, 3.5f, -3.5f, 1.932997f, -3.5f, 0.0f, -3.5f, -1.932997f,
  -1.932997f, -3.5f, 0.0f, -3.5f, 1.932997f, -3.5f, 3.5f, -1.932997f,
  3.5f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_circle4_0 = {path_circle4_0Ops, path_circle4_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::vg::Shape shapes_circle4[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_circle4_0, {0xFFCDB8FFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_circle4 = {shapes_circle4, 1, 0, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_circle4[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_circle4},
};

static const uint8_t path_circle5_0Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_circle5_0Coords[] = {
  3.5f, 0.0f, 3.5f, 1.932997f, 1.932997f, 3.5f, 0.0f, 3.5f,
  -1.932997f, 3.5f, -3.5f, 1.932997f, -3.5f, 0.0f, -3.5f, -1.932997f,
  -1.932997f, -3.5f, 0.0f, -3.5f, 1.932997f, -3.5f, 3.5f, -1.932997f,
  3.5f, 0.0f,
};
static const shapoco::gfx2d::vg::Path path_circle5_0 = {path_circle5_0Ops, path_circle5_0Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::vg::Shape shapes_circle5[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_circle5_0, {0xFFFFCBA4u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_circle5 = {shapes_circle5, 1, 0, {-3.5f, -3.5f, 7.0f, 7.0f}};

static const shapoco::gfx2d::rig::Attachment attachments_circle5[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_circle5},
};

static const uint8_t path_g6_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
  OP_CLOSE,
};
static const float path_g6_0Coords[] = {
  0.0f, -4.5f, 1.22f, -1.68f, 4.26f, -1.39f, 1.98f, 0.64f,
  2.63f, 3.63f, 0.0f, 2.08f, -2.63f, 3.63f, -1.98f, 0.64f,
  -4.26f, -1.39f, -1.22f, -1.68f,
};
static const shapoco::gfx2d::vg::Path path_g6_0 = {path_g6_0Ops, path_g6_0Coords, 11, 20, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::vg::Shape shapes_g6[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g6_0, {0xFFFFB3D1u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_g6 = {shapes_g6, 1, 0, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::rig::Attachment attachments_g6[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_g6},
};

static const uint8_t path_g7_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
  OP_CLOSE,
};
static const float path_g7_0Coords[] = {
  0.0f, -4.5f, 1.22f, -1.68f, 4.26f, -1.39f, 1.98f, 0.64f,
  2.63f, 3.63f, 0.0f, 2.08f, -2.63f, 3.63f, -1.98f, 0.64f,
  -4.26f, -1.39f, -1.22f, -1.68f,
};
static const shapoco::gfx2d::vg::Path path_g7_0 = {path_g7_0Ops, path_g7_0Coords, 11, 20, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::vg::Shape shapes_g7[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g7_0, {0xFFFFE680u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_g7 = {shapes_g7, 1, 0, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::rig::Attachment attachments_g7[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_g7},
};

static const uint8_t path_g8_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
  OP_CLOSE,
};
static const float path_g8_0Coords[] = {
  0.0f, -4.5f, 1.22f, -1.68f, 4.26f, -1.39f, 1.98f, 0.64f,
  2.63f, 3.63f, 0.0f, 2.08f, -2.63f, 3.63f, -1.98f, 0.64f,
  -4.26f, -1.39f, -1.22f, -1.68f,
};
static const shapoco::gfx2d::vg::Path path_g8_0 = {path_g8_0Ops, path_g8_0Coords, 11, 20, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::vg::Shape shapes_g8[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g8_0, {0xFFA8EED5u, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_g8 = {shapes_g8, 1, 0, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::rig::Attachment attachments_g8[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_g8},
};

static const uint8_t path_g9_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
  OP_CLOSE,
};
static const float path_g9_0Coords[] = {
  0.0f, -4.5f, 1.22f, -1.68f, 4.26f, -1.39f, 1.98f, 0.64f,
  2.63f, 3.63f, 0.0f, 2.08f, -2.63f, 3.63f, -1.98f, 0.64f,
  -4.26f, -1.39f, -1.22f, -1.68f,
};
static const shapoco::gfx2d::vg::Path path_g9_0 = {path_g9_0Ops, path_g9_0Coords, 11, 20, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::vg::Shape shapes_g9[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g9_0, {0xFFA8D8FFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_g9 = {shapes_g9, 1, 0, {-4.26f, -4.5f, 8.52f, 8.13f}};

static const shapoco::gfx2d::rig::Attachment attachments_g9[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_g9},
};

static const uint8_t path_g11_0Ops[] = {
  OP_MOVE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE, OP_LINE,
  OP_CLOSE,
};
static const float path_g11_0Coords[] = {
  0.0f, -14.0f, 3.82f, -5.26f, 13.31f, -4.33f, 6.18f, 2.01f,
  8.23f, 11.33f, 0.0f, 6.5f, -8.23f, 11.33f, -6.18f, 2.01f,
  -13.31f, -4.33f, -3.82f, -5.26f,
};
static const shapoco::gfx2d::vg::Path path_g11_0 = {path_g11_0Ops, path_g11_0Coords, 11, 20, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-13.31f, -14.0f, 26.62f, 25.33f}};

static const uint8_t path_g11_1Ops[] = {
  OP_MOVE, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CUBIC, OP_CLOSE,
};
static const float path_g11_1Coords[] = {
  -1.3f, -4.5f, -1.3f, -3.726801f, -2.284974f, -3.1f, -3.5f, -3.1f,
  -4.715026f, -3.1f, -5.7f, -3.726801f, -5.7f, -4.5f, -5.7f, -5.273199f,
  -4.715026f, -5.9f, -3.5f, -5.9f, -2.284974f, -5.9f, -1.3f, -5.273199f,
  -1.3f, -4.5f,
};
static const shapoco::gfx2d::vg::Path path_g11_1 = {path_g11_1Ops, path_g11_1Coords, 6, 26, shapoco::gfx2d::vg::FillRule::NONZERO, {0, 0, 0}, {-5.7f, -5.9f, 4.4f, 2.8f}};

static const shapoco::gfx2d::vg::Shape shapes_g11[] = {
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g11_0, {0xFFFFE680u, nullptr}, {0xFFFFE680u, nullptr}, {3.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::ROUND, {0, 0}, 4.0f}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr},
  {shapoco::gfx2d::vg::ShapeKind::PATH, 0, {0, 0}, &path_g11_1, {0xBFFFFFFFu, nullptr}, {0x00000000u, nullptr}, {1.0f, shapoco::gfx2d::vg::LineCap::BUTT, shapoco::gfx2d::vg::LineJoin::MITER, {0, 0}, 4.0f}, {0.8191521f, -0.5735765f, 0.5735765f, 0.8191521f, 1.948126f, -2.821333f}, nullptr},
};
static const shapoco::gfx2d::vg::Picture picture_g11 = {shapes_g11, 2, 0, {-14.81f, -15.5f, 29.62f, 28.33f}};

static const shapoco::gfx2d::rig::Attachment attachments_g11[] = {
  {nullptr, {0, 0, 0, 0}, {1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f}, nullptr, 0, shapoco::gfx2d::rig::AttachmentKind::VECTOR, {0, 0}, &picture_g11},
};

static const shapoco::gfx2d::rig::Bone bones[] = {
  {"root", 0.0f, 0.0f, 0, 0, 4096, 4096, 0xFF, 0},
  {"circle1", 32.0f, 32.0f, 0, 0, 4096, 4096, 0, 0},
  {"circle1_pos", 0.0f, 0.0f, 0, 0, 4096, 4096, 1, 0},
  {"circle2", 32.0f, 32.0f, 0, 0, 4096, 4096, 0, 0},
  {"circle2_pos", 8.0f, 0.0f, 0, 0, 4096, 4096, 3, 0},
  {"circle3", 32.0f, 32.0f, 16384, 16384, 4096, 4096, 0, 0},
  {"circle3_pos", 8.0f, 0.0f, 0, 0, 4096, 4096, 5, 0},
  {"circle4", 32.0f, 32.0f, -32768, -32768, 4096, 4096, 0, 0},
  {"circle4_pos", 8.0f, 0.0f, 0, 0, 4096, 4096, 7, 0},
  {"circle5", 32.0f, 32.0f, -16384, -16384, 4096, 4096, 0, 0},
  {"circle5_pos", 8.0f, 0.0f, 0, 0, 4096, 4096, 9, 0},
  {"g6_base", 32.0f, 32.0f, 8192, 8192, 4096, 4096, 0, 0},
  {"g6", 0.0f, 0.0f, 0, 0, 4096, 4096, 11, 0},
  {"g7_base", 32.0f, 32.0f, 24576, 24576, 4096, 4096, 0, 0},
  {"g7", 0.0f, 0.0f, 0, 0, 4096, 4096, 13, 0},
  {"g8_base", 32.0f, 32.0f, -24576, -24576, 4096, 4096, 0, 0},
  {"g8", 0.0f, 0.0f, 0, 0, 4096, 4096, 15, 0},
  {"g9_base", 32.0f, 32.0f, -8192, -8192, 4096, 4096, 0, 0},
  {"g9", 0.0f, 0.0f, 0, 0, 4096, 4096, 17, 0},
  {"g10_base", 32.0f, 32.0f, 0, 0, 4096, 4096, 0, 0},
  {"g10", 0.0f, 0.0f, 0, 0, 4096, 4096, 19, 0},
  {"g11", 0.0f, 0.0f, 0, 0, 4096, 4096, 20, 0},
};

static const shapoco::gfx2d::rig::Slot slots[] = {
  {"circle1", attachments_circle1, 1, 0, 2, 0, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"circle2", attachments_circle2, 1, 0, 4, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"circle3", attachments_circle3, 1, 0, 6, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"circle4", attachments_circle4, 1, 0, 8, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"circle5", attachments_circle5, 1, 0, 10, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"g6", attachments_g6, 1, 0, 12, 0, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"g7", attachments_g7, 1, 0, 14, 0, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"g8", attachments_g8, 1, 0, 16, 0, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"g9", attachments_g9, 1, 0, 18, 0, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
  {"g11", attachments_g11, 1, 0, 21, 255, shapoco::gfx2d::BlendMode::ALPHA, 0, 0, 0, nullptr, 0, {0, 0, 0}, 0.0f},
};

static const shapoco::gfx2d::rig::Armature armature = {
  "root", bones, slots, 22, 10,
  false, 0x00000000u,
  {0.0f, 0.0f, 64.0f, 64.0f},
  0x748BEB6Cu,
  shapoco::gfx2d::rig::FEATURE_SLOT_COLOR | shapoco::gfx2d::rig::FEATURE_STROKE_WIDTH,
};

// animation "main": 45 frames at 30 fps
static const shapoco::gfx2d::rig::Curve anim_main_curves[] = {
  {{0, 3930, 7296, 9895, 11775, 13107, 14056, 14739, 15236, 15600, 15865, 16057, 16193, 16285, 16344, 16375, 16384}},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone2_scale[] = {
  {0, 0xFE, 0, 4096, 4096},
  {5, 0x00, 0, 4096, 4096},
  {13, 0xFE, 0, 18432, 18432},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone4_translate[] = {
  {0, 0xFE, 0, 0.0f, 0.0f},
  {5, 0x00, 0, 0.0f, 0.0f},
  {27, 0xFF, 0, 18.0f, 0.0f},
  {45, 0xFE, 0, 19.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone4_scale[] = {
  {0, 0xFE, 0, 0, 0},
  {5, 0xFF, 0, 0, 0},
  {8, 0xFF, 0, 4096, 4096},
  {22, 0xFF, 0, 2341, 2341},
  {34, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone6_translate[] = {
  {0, 0xFE, 0, 0.0f, 0.0f},
  {5, 0x00, 0, 0.0f, 0.0f},
  {27, 0xFF, 0, 18.0f, 0.0f},
  {45, 0xFE, 0, 19.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone6_scale[] = {
  {0, 0xFE, 0, 0, 0},
  {5, 0xFF, 0, 0, 0},
  {8, 0xFF, 0, 4096, 4096},
  {22, 0xFF, 0, 2341, 2341},
  {34, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone8_translate[] = {
  {0, 0xFE, 0, 0.0f, 0.0f},
  {5, 0x00, 0, 0.0f, 0.0f},
  {27, 0xFF, 0, 18.0f, 0.0f},
  {45, 0xFE, 0, 19.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone8_scale[] = {
  {0, 0xFE, 0, 0, 0},
  {5, 0xFF, 0, 0, 0},
  {8, 0xFF, 0, 4096, 4096},
  {22, 0xFF, 0, 2341, 2341},
  {34, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone10_translate[] = {
  {0, 0xFE, 0, 0.0f, 0.0f},
  {5, 0x00, 0, 0.0f, 0.0f},
  {27, 0xFF, 0, 18.0f, 0.0f},
  {45, 0xFE, 0, 19.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone10_scale[] = {
  {0, 0xFE, 0, 0, 0},
  {5, 0xFF, 0, 0, 0},
  {8, 0xFF, 0, 4096, 4096},
  {22, 0xFF, 0, 2341, 2341},
  {34, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone12_translate[] = {
  {0, 0xFE, 0, 8.0f, 0.0f},
  {5, 0x00, 0, 8.0f, 0.0f},
  {27, 0xFF, 0, 23.0f, 0.0f},
  {45, 0xFE, 0, 24.0f, 0.0f},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone14_translate[] = {
  {0, 0xFE, 0, 8.0f, 0.0f},
  {5, 0x00, 0, 8.0f, 0.0f},
  {27, 0xFF, 0, 23.0f, 0.0f},
  {45, 0xFE, 0, 24.0f, 0.0f},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone16_translate[] = {
  {0, 0xFE, 0, 8.0f, 0.0f},
  {5, 0x00, 0, 8.0f, 0.0f},
  {27, 0xFF, 0, 23.0f, 0.0f},
  {45, 0xFE, 0, 24.0f, 0.0f},
};
static const shapoco::gfx2d::rig::TranslateKey anim_main_bone18_translate[] = {
  {0, 0xFE, 0, 8.0f, 0.0f},
  {5, 0x00, 0, 8.0f, 0.0f},
  {27, 0xFF, 0, 23.0f, 0.0f},
  {45, 0xFE, 0, 24.0f, 0.0f},
};
static const shapoco::gfx2d::rig::ScaleKey anim_main_bone20_scale[] = {
  {0, 0xFF, 0, 0, 0},
  {8, 0xFF, 0, 5120, 5120},
  {13, 0xFF, 0, 3604, 3604},
  {17, 0xFF, 0, 4342, 4342},
  {22, 0xFE, 0, 4096, 4096},
  {38, 0xFF, 0, 4096, 4096},
  {45, 0xFE, 0, 0, 0},
};
static const shapoco::gfx2d::rig::RotateKey anim_main_bone21_rotate[] = {
  {0, 0xFF, 0, -7282, -7282},
  {10, 0xFF, 0, 1456, 1456},
  {18, 0xFE, 0, 0, 0},
  {38, 0xFF, 0, 0, 0},
  {45, 0xFE, 0, 3641, 3641},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot0_alpha[] = {
  {0, 0xFF, 0},
  {5, 0xFF, 230},
  {13, 0xFE, 0},
};
static const shapoco::gfx2d::rig::StrokeWidthKey anim_main_slot0_stroke_width[] = {
  {0, 0xFF, 0, 0.0f},
  {5, 0xFF, 0, 15.0f},
  {6, 0xFF, 0, 5.154051f},
  {7, 0xFF, 0, 3.235813f},
  {8, 0xFF, 0, 2.389019f},
  {9, 0xFF, 0, 1.821447f},
  {10, 0xFF, 0, 1.35275f},
  {11, 0xFF, 0, 0.9250502f},
  {12, 0xFF, 0, 0.514877f},
  {13, 0xFF, 0, 0.1111111f},
  {45, 0xFE, 0, 0.0f},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot5_alpha[] = {
  {0, 0xFE, 0},
  {5, 0xFF, 0},
  {7, 0xFE, 255},
  {22, 0xFF, 255},
  {34, 0xFE, 0},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot6_alpha[] = {
  {0, 0xFE, 0},
  {5, 0xFF, 0},
  {7, 0xFE, 255},
  {22, 0xFF, 255},
  {34, 0xFE, 0},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot7_alpha[] = {
  {0, 0xFE, 0},
  {5, 0xFF, 0},
  {7, 0xFE, 255},
  {22, 0xFF, 255},
  {34, 0xFE, 0},
};
static const shapoco::gfx2d::rig::AlphaKey anim_main_slot8_alpha[] = {
  {0, 0xFE, 0},
  {5, 0xFF, 0},
  {7, 0xFE, 255},
  {22, 0xFF, 255},
  {34, 0xFE, 0},
};
static const shapoco::gfx2d::rig::BoneTimeline anim_main_boneTimelines[] = {
  {anim_main_bone2_scale, 3, 2, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone4_translate, 4, 4, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone4_scale, 5, 4, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone6_translate, 4, 6, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone6_scale, 5, 6, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone8_translate, 4, 8, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone8_scale, 5, 8, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone10_translate, 4, 10, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone10_scale, 5, 10, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone12_translate, 4, 12, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone14_translate, 4, 14, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone16_translate, 4, 16, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone18_translate, 4, 18, shapoco::gfx2d::rig::Channel::TRANSLATE},
  {anim_main_bone20_scale, 7, 20, shapoco::gfx2d::rig::Channel::SCALE},
  {anim_main_bone21_rotate, 5, 21, shapoco::gfx2d::rig::Channel::ROTATE},
};
static const shapoco::gfx2d::rig::SlotTimeline anim_main_slotTimelines[] = {
  {anim_main_slot0_alpha, 3, 0, shapoco::gfx2d::rig::Channel::ALPHA},
  {anim_main_slot0_stroke_width, 11, 0, shapoco::gfx2d::rig::Channel::STROKE_WIDTH},
  {anim_main_slot5_alpha, 5, 5, shapoco::gfx2d::rig::Channel::ALPHA},
  {anim_main_slot6_alpha, 5, 6, shapoco::gfx2d::rig::Channel::ALPHA},
  {anim_main_slot7_alpha, 5, 7, shapoco::gfx2d::rig::Channel::ALPHA},
  {anim_main_slot8_alpha, 5, 8, shapoco::gfx2d::rig::Channel::ALPHA},
};
static const shapoco::gfx2d::rig::Animation anim_main = {
  "main", 45, 30, 15, 6, 1, 0,
  anim_main_boneTimelines, anim_main_slotTimelines, nullptr, anim_main_curves,
  0x748BEB6Cu,
  shapoco::gfx2d::rig::FEATURE_STROKE_WIDTH,
};

static const shapoco::gfx2d::rig::Animation *const animations[] = {&anim_main};
static constexpr int ANIMATION_COUNT = 1;

}  // namespace pop_star

#endif
